version: "3.9"
   
services:
  db:
    container_name: composter-db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: composter-microservice
    command: bash -c "sh entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy